// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4y5BVE_ZM5iTJzFEiEXgkJBXa0E7VVFU',
    appId: '1:291250550268:web:4dd86aca7d10037d53ee79',
    messagingSenderId: '291250550268',
    projectId: 'gifting-e3708',
    authDomain: 'gifting-e3708.firebaseapp.com',
    storageBucket: 'gifting-e3708.firebasestorage.app',
    measurementId: 'G-5BLFZ975P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRhWBXD2llVK6iHDLtKEOCSKaUpwv1-Pg',
    appId: '1:291250550268:android:0d254b8020ae124953ee79',
    messagingSenderId: '291250550268',
    projectId: 'gifting-e3708',
    storageBucket: 'gifting-e3708.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuNBtqvsuKRqNKj0Y73woykqBJkeYTNMo',
    appId: '1:291250550268:ios:909243bd61ce1d4353ee79',
    messagingSenderId: '291250550268',
    projectId: 'gifting-e3708',
    storageBucket: 'gifting-e3708.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuNBtqvsuKRqNKj0Y73woykqBJkeYTNMo',
    appId: '1:291250550268:ios:909243bd61ce1d4353ee79',
    messagingSenderId: '291250550268',
    projectId: 'gifting-e3708',
    storageBucket: 'gifting-e3708.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4y5BVE_ZM5iTJzFEiEXgkJBXa0E7VVFU',
    appId: '1:291250550268:web:3d56c13ff3dfecdd53ee79',
    messagingSenderId: '291250550268',
    projectId: 'gifting-e3708',
    authDomain: 'gifting-e3708.firebaseapp.com',
    storageBucket: 'gifting-e3708.firebasestorage.app',
    measurementId: 'G-NGSL43GTJK',
  );

}